# Generated by Django 5.2.1 on 2025-05-31 19:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('message', models.CharField(default='Payment', max_length=255)),
                ('phonepe_qr', models.ImageField(upload_to='qr_codes/')),
                ('gpay_qr', models.ImageField(upload_to='qr_codes/')),
                ('paytm_qr', models.ImageField(upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
